# Generated by Django 4.2.6 on 2023-10-19 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntradaContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('idAuxiliarOrigen', models.IntegerField()),
                ('cuenta', models.CharField(max_length=30)),
                ('tipo_movimiento', models.CharField(choices=[('Debito', 'Debito'), ('Credito', 'Credito')], default='Debito', max_length=10)),
                ('fecha_asiento', models.DateTimeField(auto_now=True)),
                ('monto_asiento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('No disponible', 'No disponible')], default='Disponible', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='SistemasAuxiliares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('No disponible', 'No disponible')], default='Disponible', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='TiposDeCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('origen', models.CharField(choices=[('Debito', 'Debito'), ('Credito', 'Credito')], default='Debito', max_length=10)),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('No disponible', 'No disponible')], default='Disponible', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='TiposDeMoneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('ultima_tasa_cambiaria', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('No disponible', 'No disponible')], default='Disponible', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='CuentasContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('permite_transacciones', models.BooleanField(default=True)),
                ('nivel', models.IntegerField(choices=[(1, 'Nivel 1'), (2, 'Nivel 2'), (3, 'Nivel 3')], default=1)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('No disponible', 'No disponible')], default='Disponible', max_length=15)),
                ('cuenta_mayor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.cuentascontable')),
                ('tipodecuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tiposdecuenta')),
            ],
        ),
    ]
